Abort repo setup if repository already exists

diff --git a/setup_repo b/setup_repo
--- a/setup_repo
+++ b/setup_repo
@@ -13,9 +13,16 @@ fi
 
 REPO_PATH=""${PI_GIT_DIR}"/"${REPO_NAME}".git"
 
-mkdir -p "${REPO_PATH}"
-cd ${REPO_PATH}
-git init --bare --shared >/dev/null
-echo "Git repository ${REPO_NAME} created"
-echo $2 > description
-cd - >/dev/null
+if [ -d "${REPO_PATH}" ]
+then
+	echo "${REPO_NAME} already exists, aborting"
+	exit 1
+else
+	mkdir -p "${REPO_PATH}"
+	cd ${REPO_PATH}
+	git init --bare --shared > /dev/null
+	echo "Git repository ${REPO_NAME} created"
+	echo $2 > description
+	cd - >/dev/null
+	exit 0
+fi
